#!/bin/bash
#
# Sets up all the dependencies, etc. so you can build and test.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")" && cd ..

# shellcheck source=./utilities.bash
source script/utilities.bash

header "Fetching utilites"
go get "$@" -v \
  github.com/mitchellh/gox \
  github.com/kardianos/govendor

header "GoMetaLinter"
rm -rf bin
if [ -x /usr/local/bin/gometalinter ] && [ -z "${CI:-}" ]; then
  echo "Using system gometalinter"
else
  echo "Installing gometalinter..."
  curl -sSfL -o - https://git.io/vp6lP | sh
fi

# vim: set ft=sh :
