#!/bin/bash
#
# Sets up all the dependencies, etc. so you can build and test.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")" && cd ..

source script/utilities.bash

header "Go lang CI lint"
rm -rf bin
curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- v1.20.1

# vim: set ft=sh :
