#!/bin/bash
#
# Builds one (or more executable).
#
# Usage:
#   Just your native executable:
#      ./script/build
#   All cross compile platforms:
#      ./script/build all

set -euo pipefail
source "$(dirname "$0")/utilities.bash"
progname="go-importd"
osarch="${1:-native}"

export CGO_ENABLED=0 # Force static compiling

function dogox()
{
  gox \
    -ldflags "-s -w" \
    -osarch="$*" \
    -output="${progname}_{{.OS}}_{{.Arch}}"
}

if [[ "$osarch" == *all* ]]; then
  osarches=(
    darwin/amd64
    linux/amd64
  )

  header "Building all binaries"
  dogox "${osarches[*]}"
else
  header "Building native binary"
  govendor build \
    -ldflags "-s -w" \
    -o "$progname" \
    +local
fi

# vim: set ft=sh :
