#!/bin/bash
#
# Sets up all the dependencies, etc. so you can build and test.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")" && cd ..

source "script/utilities.bash"

# Use local version if used.
if [ -d bin ]; then
  export PATH="${PWD}/bin:${PATH}"
fi

header "Lint"
bin/golangci-lint run

# vim: set ft=sh :
