#!/bin/bash
#
# Sets up all the dependencies, etc. so you can build and test.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")" && cd ..

source "script/utilities.bash"

header "Lint"
if [ -t 1 ] && [ -t 0 ] && [ -z "${CI:-}" ]; then
  bin/golangci-lint run
else
  bin/golangci-lint run --out-format=checkstyle >lint.xml
fi

# vim: set ft=sh :
