#!/bin/bash
#
# Sets up all the dependencies, etc. so you can build and test.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")" && cd ..

# shellcheck source=./utilities.bash
source "script/utilities.bash"

# Use local version if used.
if [ -d bin ]; then
  export PATH="${PWD}/bin:${PATH}"
fi

header "Lint"
gometalinter --deadline=5m

# vim: set ft=sh :
