#!/bin/bash
#
# Runs all tests.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")" && cd ..

# shellcheck source=./utilities.bash
source script/utilities.bash

# Don't use CGO
export CGO_ENABLED=0

header "Tests"
go test -v ./...

# vim: set ft=sh :
